# This will run on Travis' 'new' container-based infrastructure
language: cpp

os:
  - linux

branches:
  only:
    - master

matrix:
  include:
    - dist: xenial

services:
  - mysql

# Install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++ libcurl4-openssl-dev libpng-dev libqt5sql5-mysql libqt5websockets5 libqt5websockets5-dev libwebsockets-dev make qt5-default qtchooser zlib1g zlib1g-dev zlibc
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `fhqtravis` CHARACTER SET utf8 COLLATE utf8_general_ci;'

install:
  - pip install --user websocket-client
  - pip install --user requests
  
# Build your code e.g. by calling make
script:
  - echo "code-check"
  - cd code-check
  - ./simple_code_checker.py --only-errors
  - cd ../
  - echo "Build unit tests"
  - cd unit-tests
  - ./build_simple.sh
  - echo "Run unit tests"
  - ./unit-tests
  - cd ../fhq-server
  - ./build_simple.sh
  - ./fhq-server -wd ../data_travis version
  - ./fhq-server -wd ../data_travis -cdc
  - mkdir -p public/games
  - ./fhq-server -wd ../data_travis -set "server_folder_public=`pwd`/public/"
  - cd ../tests
  - ./update_libfhqcli.sh
  - python run_tests.py # run tests
